[project]
name = "prip"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "androguard>=4.0",
    "frida==17.16.4",
    "lief>=1.0.0",
    "pydantic>=2.13.4",
    "rich>=15.0.0",
]

[project.scripts]
prip = "prip.cli:main"

[build-system]
requires = ["uv_build>=0.11.29,<0.12"]
build-backend = "uv_build"
